### ISSUE TITLE
Read More cards generated by post.hbs don't link anywhere

### ISSUE THREAD

**Issue by chadkluck** [mrvautin/squido#10]
When I build the site I noticed that the cards to other posts at the bottom of a post do not have a Read More button that links anywhere. The `href` is empty.

I discovered that post.hbs (currently line 30) refers to

```href="{{../this.url}}"```

If I follow the example of other templates and use `.permalink` instead of `.url` AND add a `/` at the start, it works in my instance:

```href="/{{../this.permalink}}"```

I did a quick check and did not see `.url` used anywhere else in .hbs templates so hopefully, this was the only spot.

Thanks, and keep up the good work!

**Comment by mrvautin** [comment]
Good pickup. If I'm understanding correctly, I've fixed in b21a031852e4b7c7e65cdf631b1a10294cc14b8d. Please let me know if I'm off the mark.

Thanks so much for reporting it.

**Comment by chadkluck** [comment]
That works! Thanks!
