### ISSUE TITLE
Ability to organize posts in subfolders

### ISSUE THREAD

**Issue by ricardonunesdev** [mrvautin/squido#16]
Hey @mrvautin,

Is it possible to implement the ability to allow markdown files in subfolders of `/posts`?

I changed line 11 of `lib/source.js` from this:
``` javascript
const sourceFiles = await glob(`${winPath(dir)}/*.${process.config.sourcesExt || 'markdown'}`);
```

to this (notice the double asterisks in the path):
``` javascript
const sourceFiles = await glob(`${winPath(dir)}/**/*.${process.config.sourcesExt || 'markdown'}`);
```

And now it allows me to organize the files in subfolders (like blog, pages, projects, docs, etc).

Is this something you're willing to add to the core of squido?
Do you want me to submit a PR for this?

Best regards,
Ricardo

**Comment by mrvautin** [comment]
I like this idea. There are a few things to consider. I will merge some code shortly enabling this.
