### ISSUE TITLE
Docs site search UX improvement suggestions

### ISSUE THREAD

**Issue by bmlyon** [mrvautin/squido#19]
Thanks for the docs site example with working search. Here are a few suggestions for improvements.

## No Results Found

Problem definition: To an end user, the search doesn't appear to be working.

Steps to reproduce:

1. Navigate to the Squido docs site.
1. In the left sidebar, search for something you know will return zero results.

Observed:

* To the end user, nothing appears to happen.

Expected:

* A "No results found" or similar message.

## Case Sensitivity

Steps to reproduce:

1. Create a post with a string that starts with an uppercase letter.
2. Search for that string in lowercase.

Observed:

* No results found.

Expected:

* Results found.

## Titles Not Indexed

Steps to reproduce:

1. Create a post where the title is not mentioned in the content. Example: Title: "First Post", Content: "Lorem Ipsum".
1. Search for the title.

Observed:

* No results found.

Expected:

* Search results for the post with that title.

Notes:

* This problem is likely low priority as it is unlikely that a post title would not be mentioned in the content.

**Comment by mrvautin** [comment]
Fixed
