### ISSUE TITLE
Responsive settings?

### ISSUE THREAD

**Issue by SeaDude** [mrvautin/squido#4]
Hello,
Could you guide me on what Squido setting to tweak to get portrait orientation on mobile to scale a bit smaller and center? 

**Example**: 
- In portrait orientation on mobile, the logo is cutoff on the left. 
- Should this be an .svg? I have a .png in there at the moment.
![image](https://user-images.githubusercontent.com/8636973/123526829-4fa7da80-d68f-11eb-9f70-208fa614fb23.png)
Thank you

**Comment by mrvautin** [comment]
Hi @SeaDude, the issue looks to be due to `PowerApps.Rocks!` text being one word. Maybe look to shrink the text or play around with `text-overflow` - https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by SeaDude** [comment]
Thanks for the tip. I'm a total newb here RE: Javascript :). 

**For others coming across this:**
- Right click on rendered site, `Inspect`
- Select the element on the screen you want to know more about
- Note the reference (`a.navbar-brand` in this case)
![image](https://user-images.githubusercontent.com/8636973/123666320-f4d8c500-d7ed-11eb-84f5-4f1cba286a3c.png)
- Open `layout.hbs` file and search for "brand"
- Points to the logo and the site name; the CSS class `brand` is defined here (I think)
![image](https://user-images.githubusercontent.com/8636973/123666504-1f2a8280-d7ee-11eb-873f-6ec91ea3de09.png)
- Open `style.css` and search for "brand"
- Change the `font-size` value as desired
![image](https://user-images.githubusercontent.com/8636973/123666435-0d48df80-d7ee-11eb-8667-c4196d396fc4.png)
