### ISSUE TITLE
Update reference to localhost when viewing source

### ISSUE THREAD

**Issue by SeaDude** [mrvautin/squido#5]
Hello,

When I right click / view source on the hosted site, I see references to the dev site `localhost:4965`: 
![image](https://user-images.githubusercontent.com/8636973/123580352-844e8b80-d78e-11eb-8dc9-5f3c68c25672.png)

I see in `config.js` there are `test`, `development` and `production` configs. I have the `production` `baseUrl` set to my domain name, but its not reflected in `view source`?

- How do I specify my domain name so it appears in `right click / view source`?

**Comment by mrvautin** [comment]
In `config.js` you can set the URL for each environment. The toggling of the environment is done using the `NODE_ENV`. See here for more info: https://docs.squido.org/configuration/

Depending on your hosting provider, setting the `NODE_ENV` may differ. What provider are you using to host your production website?

**Comment by SeaDude** [comment]
> The toggling of the environment is done using the `NODE_ENV`.

This is what I needed to know. I'm using Azure DevOps to build. Will see if I can define an `ENV` variable in the build steps to handle this. 

Cool! Much thanks for all the back and forth. Do you have a "Buy me a coffee" / Patreon / etc. link?

**Comment by mrvautin** [comment]
Azure allows the setting of environment variables here: https://docs.microsoft.com/en-us/azure/app-service/configure-common
