### ISSUE TITLE
Partial include files

### ISSUE THREAD

**Issue by bmlyon** [mrvautin/squido#6]
Hi,

I'm really liking Squido so far. In the spirit of DRY code, I can't figure out how to include partial files in Squido using Handlebars.

In the Squido docs site example, the markup for the sidebar is repeated in 3 files (index, page, post). It would be great if there were a way to load a single file that defined the sidebar outside of those files.

Any suggestions how I could go about that? Maybe something like this https://stackoverflow.com/a/12700409, but I couldn't figure out how to do that within the context of Squido.

**Comment by mrvautin** [comment]
Thanks for raising @bmlyon. It was on the list of functionality to add but it slipped my mind. I will add over the next few days and update this issue.

**Comment by mrvautin** [comment]
Added Partials in v1.0.21. A small guide can be found here: https://docs.squido.org/templates/#partials

Let me know if you have any issues.
