### ISSUE TITLE
Trouble getting partials to work using handlebars

### ISSUE THREAD

**Issue by bmlyon** [mrvautin/squido#7]
Thanks for implementing partials. I'm having trouble getting them to work. The site I'm working on is based off of the Squido docs example.

* I ran `npm update`
* I can see that the node library was updated and contains the same changes from https://github.com/mrvautin/squido/commit/4cf58466a05290e4b25d8e49cda06504d919e627#diff-ce403d6ec5029de295afb2ce2cd750756ec521b775ea915839260a778f8772ebR291
* I make a new folder, `/source/partials/filename.hbs`
* I edit the file /source/index.hbs and add `{{> filename}}`
* I run `squido serve -b -w -c`
* I can see the files build
* The terminal logs `copied: /build/partials/filename.hbs`
* Then I receive
  * `Error trying to build the index file`
  * `Error: The partial filename could not be found`
* I also tried using the partial on `/layouts/layout.hbs` and had a similar result.

Any suggestions?

In case it matters, my node version is stable (16.6.2) via nvm, and I'm running Windows Subsystem for Linux 2 with Ubuntu 20.04.2 LTS.

edit: I've temporarily made my git repository public. You can see what I had before the steps above starting at npm update. https://gitlab.com/brandonmlyon/keebl

**Comment by mrvautin** [comment]
Could you try grabbing the latest version from Github and trying again? I've made some other changes. Testing on Windows is most difficult for me as I don't have a Windows machine available.

In your repo I can't see your `/source/partials` folder. Have you not committed it?

**Comment by bmlyon** [comment]
Thanks, I couldn't get the latest build from git to install on my machine, but I was able to get this to work by installing the latest from npm. I think this might have been a P.E.B.K.A.C error. I updated my npm package lock in the project I was working on but forgot to update my global squido package.

I appreciate all of your hard work on this project! Thanks for the quick replies.

**Comment by mrvautin** [comment]
Great! I'm glad you got it working. Thanks for using and making suggestions to make `squido` better!
